theme: jekyll-theme-cayman
title: Welcome to some personal projects during my time at IE University!
description: The following projects are what I consider to be the best showcase of my range and depth of skills
